name: Paintball
main: me.blablubbabc.paintball.Paintball
version: 1.0.7Pre4
author: blablubbabc
description: Paintball by blablubbabc.
commands:
    pb:
      description: Paintball commands.
      usage: /<command>