name: Paintball
main: me.blablubbabc.paintball.Paintball
version: 1.1.8
author: blablubbabc
description: Paintball by blablubbabc.
softdepend: [InSigns, TagAPI, Multiverse-Core, My Worlds, Transporter, Multiworld]
commands:
    pb:
      description: Paintball commands.
      usage: /<command>