name: Paintball
main: me.blablubbabc.paintball.Paintball
version: 1.1.3
author: blablubbabc
description: Paintball by blablubbabc.
softdepend: [InSigns]
commands:
    pb:
      description: Paintball commands.
      usage: /<command>