name: Paintball
main: de.blablubbabc.paintball.Paintball
version: 1.3.1
author: blablubbabc
description: Paintball by blablubbabc.
softdepend: [InSigns, TagAPI, Votifier, Vault, Multiverse-Core, My Worlds, Transporter, Multiworld]
commands:
    pb:
      description: Paintball commands.
      usage: /<command>
permissions:
    paintball.general:
        description: Allows a player to play paintball.
        default: true
    paintball.admin:
        description: Access to admin and arena commands.
        default: op