name: Paintball
main: me.blablubbabc.paintball.Paintball
version: 1.1.4b
author: blablubbabc
description: Paintball by blablubbabc.
softdepend: [InSigns, TagAPI]
commands:
    pb:
      description: Paintball commands.
      usage: /<command>