name: Paintball
version: '${pluginVersion}'
authors: [blablubbabc]
website: '${dboUrl}'
description: '${pluginDescription}'

main: de.blablubbabc.paintball.Paintball
api-version: '1.20.6'

# Load after world management plugins and soft dependencies:
softdepend: [InSigns, Votifier, Vault, Multiverse-Core, My Worlds, Transporter, Multiworld, PerWorldInventory, PlaceholderAPI]

commands:
    paintball:
      description: 'Paintball base command.'
      aliases: [pb]
      usage: '/<command>'

permissions:
    paintball.general:
        description: 'Access to general player commands.'
        default: true
    paintball.admin:
        description: 'Access to admin and arena commands.'
        default: op
        children:
            paintball.general: true
